# Generated by Django 5.0.6 on 2024-05-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weeklyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.CharField(max_length=70, unique=True)),
                ('orderModel', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('orderQty', models.IntegerField()),
                ('family', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('finishDate', models.DateField()),
                ('endDate', models.DateField()),
                ('priority', models.IntegerField()),
                ('weeklyNumber', models.IntegerField()),
            ],
        ),
    ]
